- liquid-prep-app/src/app/components/my-crops/my-crops.component.html
- liquid-prep-app/src/app/components/my-crops/my-crops.component.scss
- liquid-prep-app/src/app/components/my-crops/my-crops.component.ts
- liquid-prep-app/src/app/components/select-crop/select-crop.component.html
- liquid-prep-app/src/app/components/select-crop/select-crop.component.scss
Describe at a high level the solution you're providing
Updated View all Crops page to reflect the most recent designs
Is this a patch, a minor version change, or a major version change
major
Is this related to an open issue?
https://github.com/Liquid-Prep/LiquidPrep-App/issues/17
Additional context
Last irrigated date is not yet implemented
Need design for edit button
> View All Crops Page

- liquid-prep-app/src/app/app.module.ts
- liquid-prep-app/src/app/components/settings/settings.component.html
- liquid-prep-app/src/app/components/settings/settings.component.scss
- liquid-prep-app/src/app/components/settings/settings.component.ts
- liquid-prep-app/src/app/material/material.module.ts
- liquid-prep-app/src/styles.scss
A clear and concise description of what you changed.
> Settings page

- liquid-prep-app/src/app/app.component.html
- liquid-prep-app/src/app/app.component.scss
- liquid-prep-app/src/app/app.component.ts
- liquid-prep-app/src/app/app.module.ts
- liquid-prep-app/src/app/components/dashboard/dashboard.component.html
- liquid-prep-app/src/app/components/dashboard/dashboard.component.ts
- liquid-prep-app/src/app/components/hamburger-menu/hamburger-menu.component.html
- liquid-prep-app/src/app/components/hamburger-menu/hamburger-menu.component.scss
- liquid-prep-app/src/app/components/hamburger-menu/hamburger-menu.component.spec.ts
- liquid-prep-app/src/app/components/hamburger-menu/hamburger-menu.component.ts
- liquid-prep-app/src/app/components/header-title/header-title.component.html
- liquid-prep-app/src/app/components/header-title/header-title.component.scss
- liquid-prep-app/src/app/components/header-title/header-title.component.ts
- liquid-prep-app/src/app/components/measure-soil/measure-soil.component.html
- liquid-prep-app/src/app/components/measure-soil/measure-soil.component.ts
- liquid-prep-app/src/app/components/my-crops/my-crops.component.html
- liquid-prep-app/src/app/components/my-crops/my-crops.component.ts
- liquid-prep-app/src/app/components/past-readings/past-readings.component.html
- liquid-prep-app/src/app/components/past-readings/past-readings.component.ts
- liquid-prep-app/src/app/components/seed-date/seed-date.component.html
- liquid-prep-app/src/app/components/seed-date/seed-date.component.ts
- liquid-prep-app/src/app/components/select-crop/select-crop.component.html
- liquid-prep-app/src/app/components/select-crop/select-crop.component.ts
- liquid-prep-app/src/app/components/settings/settings.component.html
- liquid-prep-app/src/app/components/settings/settings.component.ts
- liquid-prep-app/src/app/service/header.service.ts
Added the hamburger menu
minor
https://trello.com/c/NamGzpRv/24-hamburger-menu
> Hamburger Menu

- liquid-prep-app/src/app/components/advice/advice.component.scss
- liquid-prep-app/src/app/components/dashboard/dashboard.component.scss
- liquid-prep-app/src/app/components/header-title/header-title.component.html
- liquid-prep-app/src/app/components/header-title/header-title.component.scss
- liquid-prep-app/src/app/components/my-crops/my-crops.component.html
- liquid-prep-app/src/app/components/my-crops/my-crops.component.scss
- liquid-prep-app/src/app/components/my-crops/my-crops.component.ts
- liquid-prep-app/src/app/components/select-crop/select-crop.component.html
- liquid-prep-app/src/app/components/select-crop/select-crop.component.scss
- liquid-prep-app/src/app/components/test-sensor/test-sensor.component.ts
- liquid-prep-app/src/app/service/sensor.service.ts
- liquid-prep-app/src/styles.scss
Updated my crops and select crops page to fix UI issues
minor.
https://trello.com/c/OwRO6B92
> UI issues: My Crops Page

- liquid-prep-app/src/app/app-routing.module.ts
- liquid-prep-app/src/app/components/advice/advice.component.ts
- liquid-prep-app/src/app/components/dashboard/dashboard.component.html
- liquid-prep-app/src/app/components/dashboard/dashboard.component.ts
- liquid-prep-app/src/app/components/hamburger-menu/hamburger-menu.component.scss
- liquid-prep-app/src/app/components/measure-soil/measure-soil.component.html
- liquid-prep-app/src/app/components/measure-soil/measure-soil.component.ts
- liquid-prep-app/src/app/components/my-crops/my-crops.component.html
- liquid-prep-app/src/app/components/past-readings/past-readings.component.html
- liquid-prep-app/src/app/components/seed-date/seed-date.component.html
- liquid-prep-app/src/app/components/seed-date/seed-date.component.ts
- liquid-prep-app/src/app/components/select-crop/select-crop.component.html
- liquid-prep-app/src/app/components/select-crop/select-crop.component.scss
- liquid-prep-app/src/app/components/select-crop/select-crop.component.ts
- liquid-prep-app/src/app/components/test-sensor/test-sensor.component.ts
- liquid-prep-app/src/app/service/header.service.ts
- liquid-prep-app/src/manifest.webmanifest
Updated header nav component color scheme.
Changed the Hamburger menu to wrap only the dashboard component.
minor
https://trello.com/c/T7iODfAB
> [BUG]: Header Nav Issues

- liquid-prep-app/src/app/app-routing.module.ts
- liquid-prep-app/src/app/app.module.ts
- liquid-prep-app/src/app/components/dashboard/dashboard.component.html
- liquid-prep-app/src/app/components/dashboard/dashboard.component.scss
- liquid-prep-app/src/app/components/dashboard/fields/fields.component.html
- liquid-prep-app/src/app/components/dashboard/fields/fields.component.spec.ts
- liquid-prep-app/src/app/components/dashboard/fields/fields.component.ts
- liquid-prep-app/src/app/components/dashboard/home/home.component.html
- liquid-prep-app/src/app/components/dashboard/home/home.component.spec.ts
- liquid-prep-app/src/app/components/dashboard/home/home.component.ts
- liquid-prep-app/src/app/components/dashboard/sensors/sensors.component.html
- liquid-prep-app/src/app/components/dashboard/sensors/sensors.component.spec.ts
- liquid-prep-app/src/app/components/dashboard/sensors/sensors.component.ts
new dashboard framework which contains 3 sub-components: sensors, home, field
major.
[dashboard](https://trello.com/c/4yO4xHCQ/19-dashboard-home-page)
we need to implement the each sub-component
> new dashboard implementaion with bottom nav bar

- liquid-prep-app/src/app/app-routing.module.ts
- liquid-prep-app/src/app/app.module.ts
- liquid-prep-app/src/app/components/measure-soil/measure-soil.component.ts
- liquid-prep-app/src/app/components/my-crops/my-crops.component.ts
- liquid-prep-app/src/app/components/watering-insights/moisture-logs/moisture-logs.component.html
- liquid-prep-app/src/app/components/watering-insights/moisture-logs/moisture-logs.component.scss
- liquid-prep-app/src/app/components/watering-insights/moisture-logs/moisture-logs.component.spec.ts
- liquid-prep-app/src/app/components/watering-insights/moisture-logs/moisture-logs.component.ts
- liquid-prep-app/src/app/components/watering-insights/watering-insights.component.html
- liquid-prep-app/src/app/components/watering-insights/watering-insights.component.scss
- liquid-prep-app/src/app/components/watering-insights/watering-insights.component.spec.ts
- liquid-prep-app/src/app/components/watering-insights/watering-insights.component.ts
> This is the watering insights page in order to view soil moisture level and plant advices.
This is a feature based on Figma.
No this is not related to any issues
This is the Watering Insights Page which also uses the Sensor Mock data and uses local storage to store crop and advice data.
> Watering insights page

- liquid-prep-app/src/app/app-routing.module.ts
- liquid-prep-app/src/app/app.module.ts
- liquid-prep-app/src/app/components/dashboard/fields/add-field/add-field.component.html
- liquid-prep-app/src/app/components/dashboard/fields/add-field/add-field.component.scss
- liquid-prep-app/src/app/components/dashboard/fields/add-field/add-field.component.spec.ts
- liquid-prep-app/src/app/components/dashboard/fields/add-field/add-field.component.ts
- liquid-prep-app/src/app/components/dashboard/fields/details/details.component.html
- liquid-prep-app/src/app/components/dashboard/fields/details/details.component.scss
- liquid-prep-app/src/app/components/dashboard/fields/details/details.component.spec.ts
- liquid-prep-app/src/app/components/dashboard/fields/details/details.component.ts
- liquid-prep-app/src/app/components/dashboard/fields/edit-field/edit-field.component.html
- liquid-prep-app/src/app/components/dashboard/fields/edit-field/edit-field.component.scss
- liquid-prep-app/src/app/components/dashboard/fields/edit-field/edit-field.component.spec.ts
- liquid-prep-app/src/app/components/dashboard/fields/edit-field/edit-field.component.ts
- liquid-prep-app/src/app/components/dashboard/fields/fields.component.html
- liquid-prep-app/src/app/components/dashboard/fields/fields.component.scss
- liquid-prep-app/src/app/components/dashboard/fields/fields.component.ts
- liquid-prep-app/src/app/components/dashboard/fields/sensor-list/sensor-list.component.html
- liquid-prep-app/src/app/components/dashboard/fields/sensor-list/sensor-list.component.scss
- liquid-prep-app/src/app/components/dashboard/fields/sensor-list/sensor-list.component.spec.ts
- liquid-prep-app/src/app/components/dashboard/fields/sensor-list/sensor-list.component.ts
- liquid-prep-app/src/app/models/Field.ts
- liquid-prep-app/src/app/service/FieldDataService.ts
This is a feature patch
This is a feature patch
This is not related to a feature but this is one of the designs
Note: The sensors there is a placeholder since I am waiting for the list of sensors available and the soil type is a placeholder but I can update it anytime if needed.
> Fields Landing Page Updates

- liquid-prep-app/package-lock.json
- liquid-prep-app/package.json
- liquid-prep-app/src/app/app.module.ts
- liquid-prep-app/src/app/components/dashboard/dashboard.component.html
- liquid-prep-app/src/app/components/dashboard/home/home.component.html
- liquid-prep-app/src/app/components/dashboard/home/home.component.scss
- liquid-prep-app/src/app/components/dashboard/home/home.component.ts
- liquid-prep-app/src/app/components/dashboard/home/water-confirm-dialog.component.spec.ts
- liquid-prep-app/src/app/components/dashboard/home/water-confirm-dialog.component.ts
- liquid-prep-app/src/app/components/measure-soil/measure-soil.component.ts
- liquid-prep-app/src/app/models/Crop.ts
- liquid-prep-app/src/app/service/SoilMoistureService.ts
- liquid-prep-app/src/app/service/WaterAdviceService.ts
1. implement dashbard: home tab
2. add measurement record
3. add water date
major.
will need add field info into crop data in the future
> sub-component home

- liquid-prep-app/package-lock.json
> I have fixed the library vulnerabilities using npm audit.
> This is a security patch
> No
> This is a fix for critical vulnerabilities from npm audit.
> npm audit fix

- liquid-prep-app/src/app/components/my-crops/my-crops.component.html
center button text
minor
[TAMU-42](https://jsw.ibm.com/browse/TAMU-42)
> #TAMU-42 center button text

- liquid-prep-app/src/app/components/dashboard/fields/add-field/add-field.component.ts
- liquid-prep-app/src/app/components/dashboard/fields/edit-field/edit-field.component.ts
- liquid-prep-app/src/app/components/dashboard/home/home.component.html
- liquid-prep-app/src/app/components/dashboard/home/home.component.ts
- liquid-prep-app/src/app/components/dashboard/home/water-confirm-dialog.component.ts
- liquid-prep-app/src/app/models/Crop.ts
- liquid-prep-app/src/app/models/Field.ts
- liquid-prep-app/src/app/service/CropDataService.ts
- liquid-prep-app/src/app/service/FieldDataService.ts
- liquid-prep-app/src/app/service/WaterAdviceService.ts
replace my-crops with my fields
minor
> add crop facts to field crop & remove my crops & list by field

- liquid-prep-app/package-lock.json
- liquid-prep-app/package.json
- liquid-prep-app/src/app/components/select-crop/select-crop.module.ts
to update the angular, ng2-search-filter needs to be removed
minor
.
ng2-search-filter is not compatible
> remove ng2-search-filter

- liquid-prep-app/src/app/app.module.ts
- liquid-prep-app/src/app/components/dashboard/sensors-v2/sensors-v2.component.html
- liquid-prep-app/src/app/components/dashboard/sensors-v2/sensors-v2.component.ts
- liquid-prep-app/src/app/components/dialog/dialog.component.html
- liquid-prep-app/src/app/components/dialog/dialog.component.ts
- liquid-prep-app/src/app/components/sensor-type-and-field/sensor-type-and-field.component.html
- liquid-prep-app/src/app/components/sensor-type-and-field/sensor-type-and-field.component.spec.ts
- liquid-prep-app/src/app/components/sensor-type-and-field/sensor-type-and-field.component.ts
- liquid-prep-app/src/app/service/sensor-storage.service.ts
- liquid-prep-app/src/app/service/sensor-v2.service.ts
A clear and concise description of what you changed.
> Md manage sensor

- liquid-prep-app/src/app/components/dialog/dialog.component.html
A clear and concise description of what you changed.
> Remove character limit in sensor name

- liquid-prep-app/src/app/components/dashboard/sensors-v2/sensors-v2.component.ts
A clear and concise description of what you changed.
> Refresh after dialog response.

- liquid-prep-app/src/app/components/measure-soil/measure-soil.component.html
- liquid-prep-app/src/app/components/measure-soil/measure-soil.component.scss
- liquid-prep-app/src/app/components/measure-soil/measure-soil.component.ts
- liquid-prep-app/src/app/components/select-crop/select-crop.component.html
fix measure soil component issue after angular upgrade
minor
> fix measure soil component issue after ng upgrade

- liquid-prep-app/src/app/components/dashboard/home/home.component.html
- liquid-prep-app/src/app/components/dashboard/home/home.component.scss
- liquid-prep-app/src/app/components/dashboard/home/water-confirm-dialog.component.html
- liquid-prep-app/src/app/components/dashboard/home/water-confirm-dialog.component.ts
fix dashboard home component issue after ng upgrade
minor,
> fix dashboard home component issue after ng upgrade

- liquid-prep-app/src/app/components/dashboard/fields/add-field/add-field.component.html
- liquid-prep-app/src/app/components/dashboard/fields/add-field/add-field.component.ts
- liquid-prep-app/src/app/components/dashboard/fields/details/details.component.html
- liquid-prep-app/src/app/components/dashboard/fields/details/details.component.ts
- liquid-prep-app/src/app/components/dashboard/fields/edit-field/edit-field.component.html
- liquid-prep-app/src/app/components/dashboard/fields/edit-field/edit-field.component.ts
- liquid-prep-app/src/app/components/dashboard/fields/fields.component.html
- liquid-prep-app/src/app/components/dashboard/fields/fields.component.ts
- liquid-prep-app/src/app/components/dashboard/home/home.component.ts
- liquid-prep-app/src/app/models/Crop.ts
- liquid-prep-app/src/app/models/CropStatic.ts
- liquid-prep-app/src/app/service/FieldDataService.ts
- liquid-prep-app/src/assets/json/CropStaticInfoMapping.json
implement fields crop
minor
NA
some ui issue after ng upgrade
> fields crop

- liquid-prep-app/src/app/components/measure-soil/measure-soil.component.html
> Correct spacing measure-soil.component.html

- liquid-prep-app/src/app/components/settings/settings.component.html
moisture, not mosture
Patch.
no
> correct typo settings.component.html

- liquid-prep-app/src/app/components/dashboard/home/home.component.html
- liquid-prep-app/src/app/components/dashboard/home/home.component.scss
- liquid-prep-app/src/app/components/dashboard/home/home.component.ts
- liquid-prep-app/src/app/components/watering-insights/watering-insights.component.html
- liquid-prep-app/src/app/components/watering-insights/watering-insights.component.scss
- liquid-prep-app/src/app/components/watering-insights/watering-insights.component.ts
Updated Watering Advice Page with latest designs:
Updated soil moisture progress bar
Added Sensors card
Updated header details formatting with new title/value styles
Made field items clickable on home page to view watering advice page
Updated date format for seeding date to show full month name
Updated card styles
minor.
Watering Insights Page
> Watering Insights Page Updates
